scripts/create_istio_system.sh

Change verify-install to generate manifest and verify from manifest

Change verify-install

---

Dockerfile
scripts/create_istio_system.sh
scripts/uninstall_istio_system.sh

Added uninstall to chmod +x in dockerfile and added missing `fi` to uninstall script

Correct uninstall script

---

Dockerfile
scripts/create_istio_system.sh

Updated istio version to latest and added check for canary revision for install

Update to 1.7, add revision

---

Dockerfile

Update version to 1.6.6 so that upgrade will work. Upgrade requires latest stable release.

Update to latest istio release

---

Dockerfile

Increase Istio version to 1.6.7

Update to 1.6.7

---

Dockerfile
scripts/create_istio_system.sh
scripts/init_kubeconfig.sh
scripts/uninstall_istio_system.sh

Add analyze to check base and overlay yaml for errors (it checks for potential issues, but does not catch all)
Change namespace to pull from environment variable so it can be passed in from the chart
Add a flag to skip version and analyze checks and just install / update
Increase istio version 1.6.7 > 1.6.8

Add analyze, namespace changes, and force install flag

---

Dockerfile

Update to 1.7.0

---

Dockerfile

Update to 1.7.1

---

Dockerfile
README.md
scripts/create_istio_system.sh

Update to 1.7.3
Remove verify-install until istio resolve issues
**Issues**
https://github.com/rancher/rancher/issues/29383
https://github.com/rancher/rancher/issues/29249

Update to 1.7.3

---

Dockerfile
README.md

Update to 1.7.6
**Issue**
https://github.com/rancher/rancher/issues/29812

Update istio version to 1.7.6

---

Dockerfile
README.md

**Issue**
Istio version needs bumped for 1.8.1 installer
**Solution**
Increase Istio version
**Issue**
https://github.com/rancher/rancher/issues/30410

Change istio version to 1.8.1

---

Dockerfile

Updating istio version to 1.8.3
**Issue**
https://github.com/rancher/rancher/issues/31187

Change istio version to 1.8.3

---

Dockerfile

**Problem**
Need to release istio version 1.7.8
**Solution**
Create istio-installer for istio 1.7.8
**Issue**
https://github.com/rancher/rancher/issues/31811

Add istio version 1.7.8

---

Dockerfile

Creating installer for istio 1.8.4
**Issue**
https://github.com/rancher/rancher/issues/31761

Add istio 1.8.4

---

Dockerfile

**Issue**
https://github.com/rancher/rancher/issues/31265

Add istio version 1.9.2

---

Dockerfile

Add istio 1.8.5

---

Dockerfile

Add istio v1.9.3

---

Dockerfile

Add istio v1.8.6

---

Dockerfile
scripts/get_grafana_dashboards.sh

**Issue**
https://github.com/rancher/rancher/issues/32795
With new version released, our installer needs updated to include the latest version.

Increase version to istio 1.10.0

---

Dockerfile

Bumping Istio Version
https://github.com/rancher/rancher/issues/32795

Increase istio to v1.10.1

---

Dockerfile

https://github.com/istio/istio/releases/tag/1.9.6
Need an installer image that supports the most recent release for istio 1.9.x

Add support for istio 1.9.6

---

Dockerfile

Adding support for the latest 1.10.x istio release

Add support for istio 1.10.2

---

Dockerfile

https://github.com/rancher/rancher/issues/35009
https://github.com/rancher/istio-installer/pull/32
https://github.com/rancher/istio-installer/pull/34
https://github.com/rancher/istio-installer/pull/36
https://github.com/rancher/istio-installer/pull/37

[Backport 2.5] Add airgap changes to 1.9.8

---

Dockerfile
scripts/fetch_istio_releases.sh

Add istio 1.11.4 to the installer
Linked issue: 
https://github.com/rancher/rancher/issues/33683

add support for istio 1.11.4

---

Dockerfile
overlay/etc/nginx/nginx.conf
scripts/run.sh

Fixes: https://github.com/rancher/rancher/issues/35704

Add SLE BCI base image

---

scripts/fetch_istio_releases.sh

Fixes this error and unblock QA: https://github.com/rancher/rancher/issues/35704#issuecomment-1049841554

Add istio-version 1.11.4

---

Dockerfile
scripts/fetch_istio_releases.sh

Adds istio 1.11.7 to the installer
Linked issue:
https://github.com/rancher/rancher/issues/36568
https://github.com/rancher/rancher/issues/36575

Add support for istio 1.11.7

---

scripts/get_grafana_dashboards.sh

This PR adds check that dashboard revision exists for istio version. 
Linked issue: 
rancher/rancher#37618

[release/1.12] Add dashboard revision check

---

Dockerfile
scripts/fetch_istio_releases.sh
scripts/get_grafana_dashboards.sh

Add support for istio 1.13.3 to the installer. 
Linked issue: https://github.com/rancher/rancher/issues/37219

[release/1.13] Add istio 1.13.3

---

Dockerfile
scripts/fetch_istio_releases.sh

related to https://github.com/rancher/rancher/issues/38451

update for istio 1.14.3

---

Dockerfile
scripts/fetch_istio_releases.sh

Add installer support for istio 1.15.3
Related issues: https://github.com/rancher/rancher/issues/39343

[release/1.15] Add istio 1.15.3

---

Dockerfile
scripts/fetch_istio_releases.sh

Add installer support for istio 1.16.3
Related issues: https://github.com/rancher/rancher/issues/40959

[release/1.16] Add istio 1.16.3

---

Dockerfile
scripts/fetch_istio_releases.sh

Adding installer support for **Istio 1.19.0**
Related Issue: https://github.com/rancher/rancher/issues/42905
Related PRs: 
- [Image-Mirror Istio-PR](https://github.com/rancher/image-mirror/pull/471)

[release/1.19] Add istio Istio 1.19.0

---

Dockerfile

Reverts rancher/istio-installer#69

Revert "Update Dockerfile to support arm64"

---

Dockerfile
scripts/fetch_istio_releases.sh

Related issue: https://github.com/rancher/rancher/issues/44137
Related PR on image-mirror: https://github.com/rancher/image-mirror/pull/588

adding istio 1.20.3

---

Dockerfile
scripts/fetch_istio_releases.sh
scripts/get_grafana_dashboards.sh

1st Commit: Updates the base image to bci-micro:15.6
2nd Commit: Optimize image size (around 60% smaller) by removing unnecessary istio files

Updating base image

---

Dockerfile
README.md
scripts/fetch_istio_releases.sh

Istio 1.23.2
