scripts/create_istio_system.sh
We will not be deploying with canary at this time due to uninstall not being available at this time
=> Remove changes for canary deployment

Dockerfile
need istio 1.6.7 with latest installer changes for upgrade testing to be made available
=> Adding old version for upgrade testing

Dockerfile, scripts/create_istio_system.sh, scripts/get_grafana_dashboards.sh, scripts/uninstall_istio_system.sh
This adds the istio Grafana dashboards for the correct istio version to the correct rancher-monitoring dashboards namespace, if rancher-monitoring is installed.
Dashboards are downloaded at build time so that the installation is not relying on grafana.com to be available or reachable (e.g. in air-gapped installations).
For easy testing I built and pushed an image to bashofmann/istio-installer:1.7.1-1 (https://hub.docker.com/repository/docker/bashofmann/istio-installer).
=> Add Grafana dashboards to rancher-monitoring if installed

scripts/create_istio_system.sh
**Problem**
When istioctl install fails, the error was not being caught and helm was replying with a successful install
**Solution**
Check the output result of the istioctl commands and error if they were not successful. 
**Issue**
https://github.com/rancher/rancher/issues/32252
=> Add a statement to catch install or upgrade failures

Dockerfile
Add istio 1.9.8 to the installer 
There are no changes needed for the installer scriptss to work for 1.9.x and 1.10.x which is why we only see a version change.
=> Add support for istio 1.9.8

Dockerfile, README.md, scripts/run.sh
**Issue**
https://github.com/rancher/rancher/issues/30842
**Problem**
Nginx user cannot bind to port 80 in all cluster environments
**Solution**
Add nginx user to sudo group and sudo run nginx
Re-worked the "How to upgrade istio version" section of the readme. It previously did not include putting the new istio version in the `istio_version_array` in addition to changing the `ENV ISTIO_VERSION`. We need to ensure we are including the version in both places so that if someone wants to edit the chart in an air-gapped environment it works as well.
=> Update user permissions

Dockerfile, scripts/run.sh
https://github.com/rancher/rancher/issues/30842
When running the `istio-installer` image to install and upgrade in rancher-istio chart, I am seeing the following errors: 
```
Installation completesed: can't create temp file '/usr/local/app/dashboards/11829.jsonXXXXXX': Permission denied
--
Thu, Sep 30 2021 11:58:47 am | configmap/istio-dashboard-11829 created
Thu, Sep 30 2021 11:58:47 am | configmap/istio-dashboard-11829 labeled
Thu, Sep 30 2021 11:58:47 am | configmap/istio-dashboard-11829 labeled
Thu, Sep 30 2021 11:58:47 am | sed: can't create temp file '/usr/local/app/dashboards/7630.jsonXXXXXX': Permission denied
Thu, Sep 30 2021 11:58:47 am | configmap/istio-dashboard-7630 created
Thu, Sep 30 2021 11:58:48 am | configmap/istio-dashboard-7630 labeled
Thu, Sep 30 2021 11:58:48 am | …
```
=> Add nginx user to dashboard directory permissions

scripts/init_kubeconfig.sh
Instead of static/default k8s service IP, use existing env variable `KUBERNETES_SERVICE_HOST`
=> Updated to work with custom service CIDR

Dockerfile, scripts/fetch_istio_releases.sh
https://github.com/rancher/rancher/issues/35341
https://github.com/rancher/rancher/issues/33824
Change istio version from 1.11.4 to 1.10.4 so I can create a tag to backport the server IP fix with Istio 1.10.4
=> Backport k8s server IP to Istio 1.10.4

README.md
Added steps that can be followed to test the docker image prior to creating a pull request in rancher/istio-installer or rancher/charts for rancher-istio changes.
=> Add manual testing steps for docker image

Dockerfile, scripts/fetch_istio_releases.sh
This PR backport SLE BCI changes to Istio 1.10.4. 
Related: https://github.com/rancher/rancher/issues/35704
=> Backport SLE BCI base image changes to Istio 1.10.4

Dockerfile, scripts/fetch_istio_releases.sh
Add istio 1.12.6 to the installer.
Linked issue:
https://github.com/rancher/rancher/issues/37218
=> [release/1.12] Add support for istio 1.12.6

scripts/uninstall_istio_system.sh
After uninstalling istio a MutatingWebhookConfiguration is left behind which causes reinstalling istio to error out. We need to cleanup this webhook in order to fix this error. This was validated and pointed out [here](https://github.com/rancher/rancher/issues/37218#issuecomment-1100244331).
This is a workaround untill upstream istio fixes this issue. https://github.com/istio/istio/issues/36905
Linked issue:
https://github.com/rancher/rancher/issues/37218
=> [release/1.12] Remove MutatingWebhookConfiguration to fix istio reinstall issue.

scripts/uninstall_istio_system.sh
Related: https://github.com/rancher/rancher/issues/35742
This will remove the old `validatingwebhookconfiguration` `istiod-istio-system` while uninstalling Istio. This is a potential fix of the above mentioned issue.
=> [1.11] Remove old `validatingwebhookconfiguration` `istiod-istio-system` while uninstalling Istio

.drone.yml
This changes the drone.io build, so that it creates an amd64 specific tag and an arm64 specific tag, after which it creates a manifest, which combines the two. 
The combined version will be published with the original tag conventions (so without the arch suffix)
Fixes https://github.com/rancher/rancher/issues/43578
=> Add support for arm64

.drone.yml
This changes the drone.io build, so that it creates an amd64 specific tag and an arm64 specific tag, after which it creates a manifest, which combines the two. 
The combined version will be published with the original tag conventions (so without the arch suffix)
Same pull request as earlier, but I was asked to create one as well for 1.18
See #67
Closes https://github.com/rancher/rancher/issues/43578
=> Add support for arm64 in 1.18

Dockerfile
Both istioctl and kubectl needed to be installed with their respective arch in mind
Fixes bug from comments in https://github.com/rancher/rancher/issues/43578
=> Update Dockerfile to support arm64

Dockerfile
#69 was reverted in #71 after @rohitsakala posted this: https://github.com/rancher/istio-installer/pull/69#issuecomment-1826684524
> @CC007 I had to revert this PR since it failed due to kubectl error. I didn't debug it.
I build the docker image myself and [pushed it to docker hub](https://hub.docker.com/layers/ccoo7/istio-installer/1.18.2-cc007-arm64/images/sha256-51a7b7026eac9352a086f931490be75f5da5db366389b76898e6de37e69825c8?context=repo). 
After doing so and using that image in Rancher's Istio chart, I had no issues during the installation:
So I believe that the issue that was experienced was a false negative. This might have been caused by reusing the same tag name (1.18.2-rancher1), therefore I suggest to update the tag this time, even if that means that the chart itself will get a …
=> Revert "Revert "Update Dockerfile to support arm64""

.github/workflows/release.yaml
I made a mistake: I thought that `on.workflow_dispatch.inputs.imageTag.default` would be used to set the value of `inputs.imageTag` when the workflow is triggered by a tag push. This is not the case: it is set to `''`. The solution is to hard-code this value to `rancher/istio-installer` when the workflow is triggered by a tag push.
=> Fix tag-triggered release workflow

Dockerfile, scripts/fetch_istio_releases.sh
=> adding istio 1.22.1
